"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { EmptyState } from "@/components/empty-state";
import { formatDate } from "@/lib/utils";
import { FileText, Sparkles, ChevronRight, Loader2 } from "lucide-react";

type Report = { id: string; title: string; createdAt: string; generatedBy: { name: string } };

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [periodDays, setPeriodDays] = useState(7);

  function load() {
    fetch("/api/reports")
      .then((r) => r.json())
      .then((data) => {
        setReports(Array.isArray(data) ? data : []);
        setLoading(false);
      });
  }

  useEffect(load, []);

  async function generate() {
    setGenerating(true);
    try {
      const res = await fetch("/api/reports/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ periodDays }),
      });
      if (res.ok) load();
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="glass-card p-6 rounded-2xl border border-[#3B1F4D] flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-glow">
        <div>
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-[#7C3AED]/15 border border-[#3B1F4D] flex items-center justify-center text-[#EF4444]">
              <FileText className="w-5 h-5" />
            </div>
            <h1 className="text-2xl font-black text-white tracking-tight">Voice-of-Customer Reports</h1>
          </div>
          <p className="text-xs text-[#A78BFA] mt-1">
            Executive digests summarizing customer sentiment, top themes, and recommended actions.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <select
            value={periodDays}
            onChange={(e) => setPeriodDays(Number(e.target.value))}
            className="glass-input rounded-xl px-3 py-2 text-xs font-bold cursor-pointer"
          >
            <option value={7} className="bg-[#0D0712]">Last 7 days</option>
            <option value={14} className="bg-[#0D0712]">Last 14 days</option>
            <option value={30} className="bg-[#0D0712]">Last 30 days</option>
          </select>
          <button
            onClick={generate}
            disabled={generating}
            className="text-xs font-black px-4 py-2 rounded-xl gradient-bg-purple-red gradient-bg-purple-red-hover text-white shadow-combinedGlow disabled:opacity-60 flex items-center gap-1.5 transition"
          >
            {generating ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                <span>Narrating AI Report...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5" />
                <span>Generate Report</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Reports List */}
      {loading ? (
        <div className="glass-card rounded-2xl p-12 text-center text-[#A78BFA]">
          <p className="text-sm font-medium">Loading reports...</p>
        </div>
      ) : reports.length === 0 ? (
        <EmptyState title="No reports yet" description="Generate your first executive Voice-of-Customer report above." />
      ) : (
        <div className="glass-card rounded-2xl border border-[#3B1F4D] divide-y divide-[#3B1F4D]/60 overflow-hidden shadow-glow">
          {reports.map((r) => (
            <Link
              key={r.id}
              href={`/reports/${r.id}`}
              className="flex items-center justify-between px-6 py-4 hover:bg-[#160D1F]/60 text-xs transition group"
            >
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-[#160D1F] border border-[#3B1F4D] flex items-center justify-center text-[#EF4444] group-hover:scale-105 transition-transform">
                  <FileText className="w-4 h-4" />
                </div>
                <div>
                  <p className="font-bold text-sm text-white group-hover:text-[#EF4444] transition">{r.title}</p>
                  <p className="text-[#A78BFA] text-[11px] mt-0.5">
                    Generated by <strong className="text-slate-200">{r.generatedBy?.name || "System"}</strong>
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-3 text-[#A78BFA]">
                <span className="font-mono text-[11px]">{formatDate(r.createdAt)}</span>
                <ChevronRight className="w-4 h-4 text-[#A78BFA] group-hover:text-[#EF4444] transition" />
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
